#pragma comment(lib,"libcef.lib")
#pragma comment(lib,"libcef_dll_wrapper.lib")
//#pragma comment(lib,"cef_sandbox.lib")

#pragma comment(lib,"advapi32.lib")
#pragma comment(lib,"user32.lib")
#pragma comment(lib,"ole32.lib")
#pragma comment(lib,"version.lib")
#pragma comment(lib,"setupapi.lib")
#pragma comment(lib,"propsys.lib")
#pragma comment(lib,"shell32.lib")
#pragma comment(lib,"winmm.lib")
#pragma comment(lib,"shlwapi.lib")
#pragma comment(lib,"powrprof.lib")
#pragma comment(lib,"delayimp.lib")
#pragma comment(lib,"ws2_32.lib")
#pragma comment(lib,"dbghelp.lib")
#pragma comment(lib,"oleaut32.lib")
#pragma comment(lib,"wbemuuid.lib")

#pragma comment(lib,"miniini.lib")
//#pragma comment(lib,"liblzma.lib")
#pragma comment(lib,"bz2.lib")
#pragma comment(lib,"zip.lib")
#pragma comment(lib,"zlib.lib")

#pragma comment(lib,"cjson.lib")
